pipeline:
  deploy-services: 
    image: flavio1110/ubuntu-util   
    when:
      event: push
      branch: [master]
    environment:
    - REGISTRY_PASSWORD=${REGISTRY_PASSWORD}
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - envsubst < "Caddyfile"
      - cp Caddyfile $HOME/Caddyfile
      - docker image prune -af      
      - docker stack deploy -c caddy-compose.yml proxy
    secrets: [ REGISTRY_PASSWORD ]