pipeline:
  deploy-caddyfile: 
    image: flavio1110/ubuntu-util   
    when:
      event: push
      branch: [master]
    environment:
    - REGISTRY_PASSWORD=${REGISTRY_PASSWORD}
    privileged: true
    volumes:
      - /etc/Caddyfile:/etc/Caddyfile
    commands:
      - envsubst < "Caddyfile"
      - cp Caddyfile /etc/Caddyfile
    secrets: [ REGISTRY_PASSWORD ]
  
  deploy-caddyservice:
    image: docker:17.04.0-ce 
    when:
      event: push
      branch: [master]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker image prune -af      
      - docker stack deploy -c caddy-compose.yml proxy