version: '3.3'

services:
  caddy:
    image: abiosoft/caddy
    ports:
      - 80:80
      - 443:443
      - 2015:2015
    networks:
      - mynet
    command: --conf /etc/Caddyfile --log stdout -email flavio1110@gmail.com -agree=true
    environment:
      - CADDYPATH=/etc/caddycerts
    volumes:
      - /srv:/srv
      - $HOME/.caddy:/etc/caddycerts
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/tooling/Caddyfile:/etc/Caddyfile
    deploy:
      restart_policy:
        condition: any
    placement:
        constraints:
          - node.labels.stack == manager

networks:
  mynet:
    external: true

#docker run -d -p 80:80 -p 443:443 -p 2015:2015 --network=mynet -e CADDYPATH=/etc/caddycerts -v /srv:/srv -v $HOME/.caddy:/etc/caddycerts -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/tooling/Caddyfile:/etc/Caddyfile abiosoft/caddy