version: '3.3'

services:
  caddy:
    image: abiosoft/caddy
    ports:
      - 80:80
      - 443:443
      - 2015:2015
    networks:
      - mynet
    command: -email flavio1110@gmail.com -agree=true
    environment:
      - CADDYPATH=/etc/caddycerts
    volumes:
      - $HOME/.caddy:/etc/caddycerts
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/tooling/Caddyfile:/etc/Caddyfile
    deploy:
      replicas: 1
      restart_policy:
        condition: any


networks:
  mynet:
    external: true
